name: Wait for URL
description: Waits for a local or remote URL to respond with a 2xx/3xx HTTP status.
author: Ole-Martin Michelsen
inputs:
  url:
    description: The URL to wait for
    required: true
  max_attempts:
    description: Maximum number of attempts
    required: false
    default: '10'
  delay:
    description: Delay in seconds between attempts
    required: false
    default: '1'

runs:
  using: node20
  main: index.js

